// <auto-generated />
using System;
using BancaPlataforma.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BancaPlataforma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BancaDbContext))]
    [Migration("20260329053926_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BancaPlataforma.Domain.Aggregates.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("agencia");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("ImagemDocumentoBase64")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagem_documento_base64");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("contas", (string)null);
                });

            modelBuilder.Entity("BancaPlataforma.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContaDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_destino_id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("BancaPlataforma.Domain.Aggregates.Conta", b =>
                {
                    b.OwnsOne("BancaPlataforma.Domain.ValueObjects.Dinheiro", "Saldo", b1 =>
                        {
                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("saldo");

                            b1.HasKey("ContaId");

                            b1.ToTable("contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.OwnsOne("BancaPlataforma.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("ContaId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Saldo")
                        .IsRequired();
                });

            modelBuilder.Entity("BancaPlataforma.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("BancaPlataforma.Domain.Aggregates.Conta", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BancaPlataforma.Domain.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid>("TransacaoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("valor");

                            b1.HasKey("TransacaoId");

                            b1.ToTable("transacoes");

                            b1.WithOwner()
                                .HasForeignKey("TransacaoId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("BancaPlataforma.Domain.Aggregates.Conta", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
